<?php 

namespace LSB\People;

function register_custom_fields() {
	
	\acf_add_local_field_group(array (
		'key' => 'lsb_custom_field_group_person',
		'title' => __('Person', 'lsb_people'),
		'fields' => array (
			array (
				'key' => 'lsb_custom_field_person_role',
				'label' => 'Rolle',
				'name' => 'role',
				'prefix' => '',
				'type' => 'radio',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'choices' => array (
					'employee' => 'Ansatt',
					'boardMember' => 'Styremedlem',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'employee',
				'layout' => 'vertical',
			),
			array (
				'key' => 'lsb_custom_field_person_photo',
				'label' => __('Foto', 'lsb_people'),
				'name' => 'photo',
				'prefix' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'return_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'lsb_custom_field_person_company',
				'label' => 'Selskap',
				'name' => 'company',
				'prefix' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'lsb_custom_field_person_role',
							'operator' => '==',
							'value' => 'boardMember',
						),
					),
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'lsb_custom_field_person_company_url',
				'label' => 'Selskapslenke',
				'name' => 'company_url',
				'prefix' => '',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'lsb_custom_field_person_role',
							'operator' => '==',
							'value' => 'boardMember',
						),
					),
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'lsb_custom_field_person_phone',
				'label' => __('Telefon', 'lsb_people'),
				'name' => 'phone',
				'prefix' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'lsb_custom_field_person_role',
							'operator' => '==',
							'value' => 'employee',
						),
					),
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'lsb_custom_field_person_mobile',
				'label' => __('Mobil', 'lsb_people'),
				'name' => 'mobile',
				'prefix' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'lsb_custom_field_person_role',
							'operator' => '==',
							'value' => 'employee',
						),
					),
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'lsb_custom_field_person_email',
				'label' => __('E-post', 'lsb_people'),
				'name' => 'email',
				'prefix' => '',
				'type' => 'email',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'lsb_custom_field_person_role',
							'operator' => '==',
							'value' => 'employee',
						),
					),
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array (
				'key' => 'lsb_custom_field_person_links',
				'label' => __('Lenker', 'lsb_people'),
				'name' => 'links',
				'prefix' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'min' => '',
				'max' => '',
				'layout' => 'table',
				'button_label' => __('Legg til', 'lsb_people'),
				'sub_fields' => array (
					array (
						'key' => 'lsb_custom_field_person_link_tag',
						'label' => __('Tittel', 'lsb_people'),
						'name' => 'tag',
						'prefix' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
					array (
						'key' => 'lsb_custom_field_person_link_url',
						'label' => __('URL', 'lsb_people'),
						'name' => 'url',
						'prefix' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
				),
			),
			array (
				'key' => 'lsb_custom_field_person_bio',
				'label' => __('Beskrivelse', 'lsb_people'),
				'name' => 'bio',
				'prefix' => '',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'default_value' => '',
				'toolbar' => 'basic',
				'media_upload' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'lsb-person',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'seamless',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array (
			1 => 'the_content',
			2 => 'excerpt',
			3 => 'custom_fields',
			4 => 'discussion',
			5 => 'comments',
			6 => 'revisions',
			7 => 'slug',
			8 => 'author',
			9 => 'format',
			10 => 'page_attributes',
			11 => 'featured_image',
			12 => 'categories',
			13 => 'tags',
			14 => 'send-trackbacks',
		),
	));
}